-- Media
local LSM = LibStub("LibSharedMedia-3.0")

LSM:Register("sound", "airforcebase", [[Interface\Addons\RillyCleanUI\media\sound\airforcebase.ogg]])
LSM:Register("sound", "garou-specialko", [[Interface\Addons\RillyCleanUI\media\sound\garouspecialko.ogg]])
LSM:Register("sound", "garou-fullko", [[Interface\Addons\RillyCleanUI\media\sound\garou-fullko.ogg]])
LSM:Register("sound", "garou-kitaa", [[Interface\Addons\RillyCleanUI\media\sound\garou-kitaa.ogg]])
LSM:Register("sound", "garou-ko", [[Interface\Addons\RillyCleanUI\media\sound\garou-ko.ogg]])
LSM:Register("sound", "GuilesThemeOrig", [[Interface\Addons\RillyCleanUI\media\sound\GuilesThemeOrig.ogg]])
LSM:Register("sound", "guilesthemeproc", [[Interface\Addons\RillyCleanUI\media\sound\guilesthemeproc.ogg]])
LSM:Register("sound", "guilesthemesnes", [[Interface\Addons\RillyCleanUI\media\sound\guilesthemesnes.ogg]])
LSM:Register("sound", "guilsethemecps2ext", [[Interface\Addons\RillyCleanUI\media\sound\guilsethemecps2ext.ogg]])
LSM:Register("sound", "kentheme+10", [[Interface\Addons\RillyCleanUI\media\sound\kentheme+10.ogg]])
LSM:Register("sound", "kentheme+5-20s", [[Interface\Addons\RillyCleanUI\media\sound\kentheme+5-20s.ogg]])
LSM:Register("sound", "kentheme+5", [[Interface\Addons\RillyCleanUI\media\sound\kentheme+5.ogg]])
LSM:Register("sound", "kentheme+8", [[Interface\Addons\RillyCleanUI\media\sound\kentheme+8.ogg]])
LSM:Register("sound", "kentheme", [[Interface\Addons\RillyCleanUI\media\sound\kentheme.ogg]])
LSM:Register("sound", "kentheme30s+10", [[Interface\Addons\RillyCleanUI\media\sound\kentheme30s+10.ogg]])
LSM:Register("sound", "kenthemebuildup+5", [[Interface\Addons\RillyCleanUI\media\sound\kenthemebuildup+5.ogg]])
LSM:Register("sound", "kenthemebuildup-.5+10db", [[Interface\Addons\RillyCleanUI\media\sound\kenthemebuildup-.5+10db.ogg]])
LSM:Register("sound", "kenthemebuildup-.5", [[Interface\Addons\RillyCleanUI\media\sound\kenthemebuildup-.5.ogg]])
LSM:Register("sound", "kenthemebuildup-.5s+5db", [[Interface\Addons\RillyCleanUI\media\sound\kenthemebuildup-.5s+5db.ogg]])
LSM:Register("sound", "kenthemebuildup", [[Interface\Addons\RillyCleanUI\media\sound\kenthemebuildup.ogg]])
LSM:Register("sound", "mario-invincibility-2secfade+10db", [[Interface\Addons\RillyCleanUI\media\sound\mario-invincibility-2secfade+10db.ogg]])
LSM:Register("sound", "mario-invincibility-2secfade", [[Interface\Addons\RillyCleanUI\media\sound\mario-invincibility-2secfade.ogg]])
LSM:Register("sound", "MinorCircuit", [[Interface\Addons\RillyCleanUI\media\sound\minorcircuit.ogg]])

LSM:Register ("statusbar", "RillyClean", [[Interface\AddOns\RillyCleanUI\media\textures\status-bar]])

LSM:Register ("font", "Andika", [[Interface\AddOns\RillyCleanUI\media\fonts\Andika.ttf]])
LSM:Register ("font", "Marmelad", [[Interface\AddOns\RillyCleanUI\media\fonts\Marmelad.ttf]])
